services:
 privatept-oai-api:
    container_name: privategpt-oai-api
    build:
      context: ../../
      dockerfile: agents/OpenAI_Compatible_API_Agent/Dockerfile
    ports:
      - 8001:8001
    volumes:
      - .:/app
